name: Build FFmpeg
on: [push]

jobs:
  setup:
    name: build ffmpeg
    runs-on: macos-13
    
    steps:
    - uses: actions/checkout@v4
    - name: build
      run: |
       mkdir _build
       cd _build
       ../build.sh
