name: Build FFmpeg
run-name: ${{ gitea.actor }} is Building FFmpeg
on: [push]

jobs:
  setup:
    name: build ffmpeg
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: build
    - run: |
       mkdir _build
       cd _build
       ../build.sh
